server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进eureka服务器的微服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CGZWade/springcloud-config.git #github路径
          search-paths:
            - springcloud-config #搜索目录
      label: master #读取分支
  rabbitmq: # rabbitMQ相关配置
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
#      defaultZone:  http://localhost:7001/eureka

# rabbitMQ相关配置，暴露BUS刷新配置的端点
# 添加完此配置后，只需在CMD发送 curl -X POST "http://localhost:3344/actuator/bus-refresh" 即可将在Github修改的配置影响到3355、3366服务中
# 也可以定点通知，curl -X POST "http://localhost:3344/actuator/bus-refresh/config-client:3355"
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

